
model:
  type: logistic_regression, # Options: logistic_regression, random_forest, svm
  max_iter: 1000
  random_state: 42

data:
  raw: data/raw/Cancer_data.csv
   

paths:
  model: src/models/logistic_model.pkl
